### ISSUE TITLE
Feedback on Milestone 1

### ISSUE THREAD

**Issue by Nazliozum** [UBC-MDS/Breast-Cancer-Prediction#25]
@akanshaVashisth @talhaadnan100 
You have made many additions to your project for this milestone. Good job! :)
Here are some of the remaining issues:

**About final report**
- [ ] Elaborate on your EDA. You give the visualization, but you do not discuss the figure at all in your report. 
- [ ] Give more details on the cross-validation process in your report. Which values were tested for which variables? How many folds were used? 
	- I would _suggest_ including a figure related to the cross validation showing how the validation score changes with different values of a variable.
- [ ] Do not add Figure numbers and captions as regular text under the figures. You can use `include_graphics()` to read in the figure and add figure caption with `fig.cap` in the chunk options.

**Other issues**
- [x] Change the structure and language of your readme in a way that it reflects your project. This is no longer a proposal. You conduct an analysis and you give the overview of the analysis as well as the directions to run your analysis on the main readme. Therefore, the readme should no longer have the remaining structure of a proposal document.
- [x] Add version information for dependencies
- [x] Fix typo on main readme: Brackets are wrong when you cite Wikipedia as "(Wikipedia)[https://en.wikipedia.org/wiki/Insulin]", I am guessing you wanted to add a link to the work Wikipedia 
- [x] Add a link to your report on the main readme
- [x] Keep your figures that are a result of your analysis in the `results/` folder. The `img/` folder is mainly for external images that you want to include in your report or elsewhere. 
- [x] Add documentation to your `eda.py` and `read_clean.py` scripts. 

**Suggestions:**

- You do not have to state "Citation Request(as requested by the data source page):" when citing the data source on the main readme
- I think that the structure of the readme, or more specifically the flow is a bit confusing. It might be more clear for the reader if you have the following flow in your main readme: motivation, the question, explanation of the data, directions on how to run your analysis, dependencies, references. You can leave it as it is, it is your choice, but this is a strong suggestion :)
- The logic behind the choice of decision tree as your model as well as the details of your analysis can be in the report. You do not have to talk about these in the readme at this point in your project.
- Keep any sort of cleaned/wrangled data file, i.e. intermediate results in the `results/` folder.
- State the Assumptions section in the beginning of your report where you introduce the data. 
- Add team members' names and github profile links on the main readme.

**Comment by talhaadnan100** [comment]
Appreciate your feedback and encouragement! Upcoming improvements to the Readme and report are captured in issues 26 and 27 respectively. We will close this issue after checking that all improvements are complete for milestone 2.

**Comment by akanshaVashisth** [comment]
Updated the report and readme as per the feedback and suggestions.
Thank you @Nazliozum for providing valuable feedback.
