### ISSUE TITLE
Update Readme with milestone 1 feedback

### ISSUE THREAD

**Issue by talhaadnan100** [UBC-MDS/Breast-Cancer-Prediction#26]
Based on feedback #25 , the following improvements are needed in the Readme:

- [ ] Change structure to motivation, the question, explanation of the data, directions on how to run your analysis, dependencies, references, team members' info (names and GitHub profile links)
- [ ] Add version information for dependencies
- [ ] Fix typo: Brackets are wrong when you cite Wikipedia as "(Wikipedia)[https://en.wikipedia.org/wiki/Insulin]"
- [ ] Add a link to your report on the main readme
