### ISSUE TITLE
Update report with milestone 1 feedback

### ISSUE THREAD

**Issue by talhaadnan100** [UBC-MDS/Breast-Cancer-Prediction#27]
Based on feedback #25  , the following improvements are needed in the report:

- [x] Elaborate on EDA explaining features visualization.
- [x] Give more details on the cross-validation process in your report. Which values were tested for which variables? How many folds were used?
- [x] Use `include_graphics()` to read in the figure and add figure caption with `fig.cap` in the chunk options
- [x] State the Assumptions section in the beginning of your report where you introduce the data

**Comment by talhaadnan100** [comment]
Report has been modified with the above improvements. Changes will be pushed to repo soon.
